name: Build and Push Docker Image CI (manual)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.REGISTRY_URL }}      
      IMAGE_NAME: teste-mateus2/kong-plugin-detection-attack
      TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build image (manual)
        run: |
          set -euo pipefail
          IMAGE="$REGISTRY/$IMAGE_NAME"
          echo "Building $IMAGE:$TAG"
          docker build -t "$IMAGE:$TAG" .

      - name: Push image (manual)
        run: |
          set -euo pipefail
          IMAGE="$REGISTRY/$IMAGE_NAME"
          echo "Pushing $IMAGE:$TAG"
          docker push "$IMAGE:$TAG"
