name: Build and Push Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USER_NE1 }}
        password: ${{ secrets.REGISTRY_PASSWORD_NE1 }}
        registry: ${{ secrets.REGISTRY_URL_NE1 }}

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_URL_NE1}}/teste-mateus/kong-plugin-detection-attack:latest
